### ISSUE TITLE
Question: How large of an L01 is libewf capable of opening?

### ISSUE THREAD

**Issue by mikebbt** [libyal/libewf-legacy#16]
I have an L01 that is 525GB+ in size that cannot be opened (error is libewf_handle_get_root_file_entry: invalid handle - missing single files.) was wondering if there is a limit?  Reviewing the code but asking in case there is a quick answer, it's also possible that the L01 was corrupted but smaller L01's seem to be ok.

**Comment by joachimmetz** [comment]
> error is libewf_handle_get_root_file_entry: invalid handle - missing single files

indicates it cannot find the single files section, so corruption is possible.

The maximum size of an L01 that libewf can handle is more dependent on the number of files entries in the single files section, less on the total size of the L01 segment files, otherwise you'll hit another limit but that would be the same for E01 segment files.

**Comment by joachimmetz** [comment]
See https://github.com/libyal/libewf/wiki/Troubleshooting#format-or-behavioral-errors for some tips on troubleshooting format incompatibility or corruption issues.

**Comment by mikebbt** [comment]
Appreciate the response, thanks.
